/**
 * @fileoverview gRPC-Web generated client stub for alis.a2a.extension.history.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.24.4
// source: alis/a2a/extension/history/v1/history.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')

var google_protobuf_field_mask_pb = require('google-protobuf/google/protobuf/field_mask_pb.js')

var google_iam_v1_policy_pb = require('@alis-build/google-common-protos/google/iam/v1/policy_pb.js')

var google_iam_v1_iam_policy_pb = require('@alis-build/google-common-protos/google/iam/v1/iam_policy_pb.js')

var alis_open_iam_v1_iam_pb = require('@open.alis.services/protobuf/alis/open/iam/v1/iam_pb.js')

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')

var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js')

var lf_a2a_v1_a2a_pb = require('@alis-build/a2a/lf/a2a/v1/a2a_pb.js')
const proto = {};
proto.alis = {};
proto.alis.a2a = {};
proto.alis.a2a.extension = {};
proto.alis.a2a.extension.history = {};
proto.alis.a2a.extension.history.v1 = require('./history_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v1.GetIamPolicyRequest,
 *   !proto.google.iam.v1.Policy>}
 */
const methodDescriptor_A2AHistoryService_GetIamPolicy = new grpc.web.MethodDescriptor(
  '/alis.a2a.extension.history.v1.A2AHistoryService/GetIamPolicy',
  grpc.web.MethodType.UNARY,
  google_iam_v1_iam_policy_pb.GetIamPolicyRequest,
  google_iam_v1_policy_pb.Policy,
  /**
   * @param {!proto.google.iam.v1.GetIamPolicyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_iam_v1_policy_pb.Policy.deserializeBinary
);


/**
 * @param {!proto.google.iam.v1.GetIamPolicyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.iam.v1.Policy)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.iam.v1.Policy>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServiceClient.prototype.getIamPolicy =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/GetIamPolicy',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_GetIamPolicy,
      callback);
};


/**
 * @param {!proto.google.iam.v1.GetIamPolicyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.iam.v1.Policy>}
 *     Promise that resolves to the response
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServicePromiseClient.prototype.getIamPolicy =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/GetIamPolicy',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_GetIamPolicy);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v1.SetIamPolicyRequest,
 *   !proto.google.iam.v1.Policy>}
 */
const methodDescriptor_A2AHistoryService_SetIamPolicy = new grpc.web.MethodDescriptor(
  '/alis.a2a.extension.history.v1.A2AHistoryService/SetIamPolicy',
  grpc.web.MethodType.UNARY,
  google_iam_v1_iam_policy_pb.SetIamPolicyRequest,
  google_iam_v1_policy_pb.Policy,
  /**
   * @param {!proto.google.iam.v1.SetIamPolicyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_iam_v1_policy_pb.Policy.deserializeBinary
);


/**
 * @param {!proto.google.iam.v1.SetIamPolicyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.iam.v1.Policy)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.iam.v1.Policy>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServiceClient.prototype.setIamPolicy =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/SetIamPolicy',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_SetIamPolicy,
      callback);
};


/**
 * @param {!proto.google.iam.v1.SetIamPolicyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.iam.v1.Policy>}
 *     Promise that resolves to the response
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServicePromiseClient.prototype.setIamPolicy =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/SetIamPolicy',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_SetIamPolicy);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.iam.v1.TestIamPermissionsRequest,
 *   !proto.google.iam.v1.TestIamPermissionsResponse>}
 */
const methodDescriptor_A2AHistoryService_TestIamPermissions = new grpc.web.MethodDescriptor(
  '/alis.a2a.extension.history.v1.A2AHistoryService/TestIamPermissions',
  grpc.web.MethodType.UNARY,
  google_iam_v1_iam_policy_pb.TestIamPermissionsRequest,
  google_iam_v1_iam_policy_pb.TestIamPermissionsResponse,
  /**
   * @param {!proto.google.iam.v1.TestIamPermissionsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_iam_v1_iam_policy_pb.TestIamPermissionsResponse.deserializeBinary
);


/**
 * @param {!proto.google.iam.v1.TestIamPermissionsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.iam.v1.TestIamPermissionsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.iam.v1.TestIamPermissionsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServiceClient.prototype.testIamPermissions =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/TestIamPermissions',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_TestIamPermissions,
      callback);
};


/**
 * @param {!proto.google.iam.v1.TestIamPermissionsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.iam.v1.TestIamPermissionsResponse>}
 *     Promise that resolves to the response
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServicePromiseClient.prototype.testIamPermissions =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/TestIamPermissions',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_TestIamPermissions);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.BatchTestIamPermissionsRequest,
 *   !proto.alis.open.iam.v1.BatchTestIamPermissionsResponse>}
 */
const methodDescriptor_A2AHistoryService_BatchTestIamPermissions = new grpc.web.MethodDescriptor(
  '/alis.a2a.extension.history.v1.A2AHistoryService/BatchTestIamPermissions',
  grpc.web.MethodType.UNARY,
  alis_open_iam_v1_iam_pb.BatchTestIamPermissionsRequest,
  alis_open_iam_v1_iam_pb.BatchTestIamPermissionsResponse,
  /**
   * @param {!proto.alis.open.iam.v1.BatchTestIamPermissionsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  alis_open_iam_v1_iam_pb.BatchTestIamPermissionsResponse.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.BatchTestIamPermissionsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.open.iam.v1.BatchTestIamPermissionsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.open.iam.v1.BatchTestIamPermissionsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServiceClient.prototype.batchTestIamPermissions =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/BatchTestIamPermissions',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_BatchTestIamPermissions,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.BatchTestIamPermissionsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.open.iam.v1.BatchTestIamPermissionsResponse>}
 *     Promise that resolves to the response
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServicePromiseClient.prototype.batchTestIamPermissions =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/BatchTestIamPermissions',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_BatchTestIamPermissions);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.AddIamBindingsRequest,
 *   !proto.google.iam.v1.Policy>}
 */
const methodDescriptor_A2AHistoryService_AddIamBindings = new grpc.web.MethodDescriptor(
  '/alis.a2a.extension.history.v1.A2AHistoryService/AddIamBindings',
  grpc.web.MethodType.UNARY,
  alis_open_iam_v1_iam_pb.AddIamBindingsRequest,
  google_iam_v1_policy_pb.Policy,
  /**
   * @param {!proto.alis.open.iam.v1.AddIamBindingsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_iam_v1_policy_pb.Policy.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.AddIamBindingsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.iam.v1.Policy)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.iam.v1.Policy>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServiceClient.prototype.addIamBindings =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/AddIamBindings',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_AddIamBindings,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.AddIamBindingsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.iam.v1.Policy>}
 *     Promise that resolves to the response
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServicePromiseClient.prototype.addIamBindings =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/AddIamBindings',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_AddIamBindings);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.open.iam.v1.RemoveIamBindingsRequest,
 *   !proto.google.iam.v1.Policy>}
 */
const methodDescriptor_A2AHistoryService_RemoveIamBindings = new grpc.web.MethodDescriptor(
  '/alis.a2a.extension.history.v1.A2AHistoryService/RemoveIamBindings',
  grpc.web.MethodType.UNARY,
  alis_open_iam_v1_iam_pb.RemoveIamBindingsRequest,
  google_iam_v1_policy_pb.Policy,
  /**
   * @param {!proto.alis.open.iam.v1.RemoveIamBindingsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_iam_v1_policy_pb.Policy.deserializeBinary
);


/**
 * @param {!proto.alis.open.iam.v1.RemoveIamBindingsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.iam.v1.Policy)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.iam.v1.Policy>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServiceClient.prototype.removeIamBindings =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/RemoveIamBindings',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_RemoveIamBindings,
      callback);
};


/**
 * @param {!proto.alis.open.iam.v1.RemoveIamBindingsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.iam.v1.Policy>}
 *     Promise that resolves to the response
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServicePromiseClient.prototype.removeIamBindings =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/RemoveIamBindings',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_RemoveIamBindings);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.a2a.extension.history.v1.ListA2AHistoriesRequest,
 *   !proto.alis.a2a.extension.history.v1.ListA2AHistoriesResponse>}
 */
const methodDescriptor_A2AHistoryService_ListA2AHistories = new grpc.web.MethodDescriptor(
  '/alis.a2a.extension.history.v1.A2AHistoryService/ListA2AHistories',
  grpc.web.MethodType.UNARY,
  proto.alis.a2a.extension.history.v1.ListA2AHistoriesRequest,
  proto.alis.a2a.extension.history.v1.ListA2AHistoriesResponse,
  /**
   * @param {!proto.alis.a2a.extension.history.v1.ListA2AHistoriesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.a2a.extension.history.v1.ListA2AHistoriesResponse.deserializeBinary
);


/**
 * @param {!proto.alis.a2a.extension.history.v1.ListA2AHistoriesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.a2a.extension.history.v1.ListA2AHistoriesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.a2a.extension.history.v1.ListA2AHistoriesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServiceClient.prototype.listA2AHistories =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/ListA2AHistories',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_ListA2AHistories,
      callback);
};


/**
 * @param {!proto.alis.a2a.extension.history.v1.ListA2AHistoriesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.a2a.extension.history.v1.ListA2AHistoriesResponse>}
 *     Promise that resolves to the response
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServicePromiseClient.prototype.listA2AHistories =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/ListA2AHistories',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_ListA2AHistories);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.a2a.extension.history.v1.GetA2AHistoryRequest,
 *   !proto.alis.a2a.extension.history.v1.A2AHistory>}
 */
const methodDescriptor_A2AHistoryService_GetA2AHistory = new grpc.web.MethodDescriptor(
  '/alis.a2a.extension.history.v1.A2AHistoryService/GetA2AHistory',
  grpc.web.MethodType.UNARY,
  proto.alis.a2a.extension.history.v1.GetA2AHistoryRequest,
  proto.alis.a2a.extension.history.v1.A2AHistory,
  /**
   * @param {!proto.alis.a2a.extension.history.v1.GetA2AHistoryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.a2a.extension.history.v1.A2AHistory.deserializeBinary
);


/**
 * @param {!proto.alis.a2a.extension.history.v1.GetA2AHistoryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.a2a.extension.history.v1.A2AHistory)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.a2a.extension.history.v1.A2AHistory>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServiceClient.prototype.getA2AHistory =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/GetA2AHistory',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_GetA2AHistory,
      callback);
};


/**
 * @param {!proto.alis.a2a.extension.history.v1.GetA2AHistoryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.a2a.extension.history.v1.A2AHistory>}
 *     Promise that resolves to the response
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServicePromiseClient.prototype.getA2AHistory =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/GetA2AHistory',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_GetA2AHistory);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.a2a.extension.history.v1.DeleteA2AHistoryRequest,
 *   !proto.alis.a2a.extension.history.v1.A2AHistory>}
 */
const methodDescriptor_A2AHistoryService_DeleteA2AHistory = new grpc.web.MethodDescriptor(
  '/alis.a2a.extension.history.v1.A2AHistoryService/DeleteA2AHistory',
  grpc.web.MethodType.UNARY,
  proto.alis.a2a.extension.history.v1.DeleteA2AHistoryRequest,
  proto.alis.a2a.extension.history.v1.A2AHistory,
  /**
   * @param {!proto.alis.a2a.extension.history.v1.DeleteA2AHistoryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.a2a.extension.history.v1.A2AHistory.deserializeBinary
);


/**
 * @param {!proto.alis.a2a.extension.history.v1.DeleteA2AHistoryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.a2a.extension.history.v1.A2AHistory)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.a2a.extension.history.v1.A2AHistory>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServiceClient.prototype.deleteA2AHistory =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/DeleteA2AHistory',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_DeleteA2AHistory,
      callback);
};


/**
 * @param {!proto.alis.a2a.extension.history.v1.DeleteA2AHistoryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.a2a.extension.history.v1.A2AHistory>}
 *     Promise that resolves to the response
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServicePromiseClient.prototype.deleteA2AHistory =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/DeleteA2AHistory',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_DeleteA2AHistory);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.a2a.extension.history.v1.AppendEventRequest,
 *   !proto.alis.a2a.extension.history.v1.AppendEventResponse>}
 */
const methodDescriptor_A2AHistoryService_AppendEvent = new grpc.web.MethodDescriptor(
  '/alis.a2a.extension.history.v1.A2AHistoryService/AppendEvent',
  grpc.web.MethodType.UNARY,
  proto.alis.a2a.extension.history.v1.AppendEventRequest,
  proto.alis.a2a.extension.history.v1.AppendEventResponse,
  /**
   * @param {!proto.alis.a2a.extension.history.v1.AppendEventRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.a2a.extension.history.v1.AppendEventResponse.deserializeBinary
);


/**
 * @param {!proto.alis.a2a.extension.history.v1.AppendEventRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.a2a.extension.history.v1.AppendEventResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.a2a.extension.history.v1.AppendEventResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServiceClient.prototype.appendEvent =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/AppendEvent',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_AppendEvent,
      callback);
};


/**
 * @param {!proto.alis.a2a.extension.history.v1.AppendEventRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.a2a.extension.history.v1.AppendEventResponse>}
 *     Promise that resolves to the response
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServicePromiseClient.prototype.appendEvent =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/AppendEvent',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_AppendEvent);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.a2a.extension.history.v1.ListEventsRequest,
 *   !proto.alis.a2a.extension.history.v1.ListEventsResponse>}
 */
const methodDescriptor_A2AHistoryService_ListEvents = new grpc.web.MethodDescriptor(
  '/alis.a2a.extension.history.v1.A2AHistoryService/ListEvents',
  grpc.web.MethodType.UNARY,
  proto.alis.a2a.extension.history.v1.ListEventsRequest,
  proto.alis.a2a.extension.history.v1.ListEventsResponse,
  /**
   * @param {!proto.alis.a2a.extension.history.v1.ListEventsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.a2a.extension.history.v1.ListEventsResponse.deserializeBinary
);


/**
 * @param {!proto.alis.a2a.extension.history.v1.ListEventsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.alis.a2a.extension.history.v1.ListEventsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.alis.a2a.extension.history.v1.ListEventsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServiceClient.prototype.listEvents =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/ListEvents',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_ListEvents,
      callback);
};


/**
 * @param {!proto.alis.a2a.extension.history.v1.ListEventsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.alis.a2a.extension.history.v1.ListEventsResponse>}
 *     Promise that resolves to the response
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServicePromiseClient.prototype.listEvents =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/ListEvents',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_ListEvents);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.alis.a2a.extension.history.v1.StreamEventsRequest,
 *   !proto.alis.a2a.extension.history.v1.A2AHistoryEvent>}
 */
const methodDescriptor_A2AHistoryService_StreamEvents = new grpc.web.MethodDescriptor(
  '/alis.a2a.extension.history.v1.A2AHistoryService/StreamEvents',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.alis.a2a.extension.history.v1.StreamEventsRequest,
  proto.alis.a2a.extension.history.v1.A2AHistoryEvent,
  /**
   * @param {!proto.alis.a2a.extension.history.v1.StreamEventsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.alis.a2a.extension.history.v1.A2AHistoryEvent.deserializeBinary
);


/**
 * @param {!proto.alis.a2a.extension.history.v1.StreamEventsRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.alis.a2a.extension.history.v1.A2AHistoryEvent>}
 *     The XHR Node Readable Stream
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServiceClient.prototype.streamEvents =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/StreamEvents',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_StreamEvents);
};


/**
 * @param {!proto.alis.a2a.extension.history.v1.StreamEventsRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.alis.a2a.extension.history.v1.A2AHistoryEvent>}
 *     The XHR Node Readable Stream
 */
proto.alis.a2a.extension.history.v1.A2AHistoryServicePromiseClient.prototype.streamEvents =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/alis.a2a.extension.history.v1.A2AHistoryService/StreamEvents',
      request,
      metadata || {},
      methodDescriptor_A2AHistoryService_StreamEvents);
};


module.exports = proto.alis.a2a.extension.history.v1;
